apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          #image: bash:latest
          image: nginx
          imagePullPolicy: "IfNotPresent"
          #command: ["/bin/sh"]
          #args: ["-c", "while true; do echo -e \"HTTP/1.1 200 OK\\n\\n$(echo Hello World)\" | nc -l -k -p 8080 -q 1; done"]
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: bash-app-svc
  namespace: bash-app
  labels:
    app: bash-app
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: bash-app
