apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-app
  namespace: bash-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bash-app
  template:
    metadata:
      labels:
        app: bash-app
    spec:
      containers:
        - name: bash-app
          image: bash:3.0.22
          #image: nginx
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo -e 'GET / HTTP/1.1\r\n\r\n\r\nPING' | nc -vN localhost 3000"]
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: bash-app-svc
  namespace: bash-app
  labels:
    app: bash-app
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: bash-app
